### PR TITLE
Add a number of basic formulas, and the definitions needed for them.

### PR DESCRIPTION
**Pull request by timoalho**
All formulas pulled from CA2GC or Chisolm's intro, http://arxiv.org/abs/1205.5935

### CODE REVIEW

**Comment by timoalho** [comment]
A part of the idea was also to have the .bib -file usable as a general GA-references file for other projects, adding the page numbers would ruin that. In addition, it would make the references in this document a royal mess eventually, there would be hundreds of lines such as "Clifford Algebra to Geometric Calculus, pp. xxx-xxx".

Of course, I get what you're aiming at, it's quite a chore to check these if you have to go through the whole book for each formula (well, these specific formulas are easily found, but later on). There's at least four options to deal with this generally that I can think of:
1) the page numbers are added to the pull request comments
2) the page numbers are added to the citations in the text itself, i.e. the Latex code would go something like ".. \cite{CA2GC}, pages xxx-xxx"
3) page numbers are not added
4) page numbers are added to the LaTex-code as comments next to the citation, and do not appear in the end product

Number 3) has the obvious disadvantage that indeed inspecting the pull requests becomes more laborious. 2) is quite non-standard, and would look funny, but would of course document the references very clearly (if you look at scientific texts in the natural sciences, citing by page number is quite rare. The humanities seem to do it much more often). That leaves 1) and 4), over which I don't really have a preference. If we go with 1), I'd probably anyway use 4) to keep track while working, though.

**Comment by lukeburns** [comment]
I prefer option 4. It'll help with PRs and anyone really interested can just take a look in the code. We can make a mention of this in the README so that people know where to look.

**Comment by timoalho** [comment]
Ok, 4) it is. I'll try to add the page numbers on Tuesday or Wednesday.

**Comment by timoalho** [comment]
Well, I decided to do that right away, instead. Also found a mistake, which I corrected. Shows the necessity for peer review, doesn't it!

**Comment by timoalho** [comment]
Well, my experience is rather that they simplify things! Specifically, when I found http://arxiv.org/abs/1205.5935 which uses contractions and has a nice list of formulas in the end, I became faster and more confident in the basic manipulations. What I mean that when using formulas such as (1.25b, c) and (1.43) in CA2GC and similar, for me it's easier to keep track that the hook points the right way rather than to track the grades of the objects explicitly. This is of course the kind of thing that depends heavily on what one is used to, and I'm sure varies person to person.

By saying that one can replace the contractions by a combination of geometric product and projection, do you mean that you can essentially always subsume the grade conditions to the exceptions already included in the definition of the projection?

Anyway,  I think this might be worth discussing with more of the people participating who are/will be involved in this project. There's an AGACSE 2015 Facebook group, with Dietmar Hildenbrand, Pierre Mechant, Nick Okamoto, Pablo Colapinto and others, so there's a reasonably diverse sampling of the community. What do you think about wrestling this matter in there? In general of course pull requests should be handled here in GitHub, but this notational matter affects basically any written output we produce.

**Comment by chrisjldoran** [comment]
Nearly all of the formulae in Chisholm's paper apply equally to the more
standard dot product, without the requirement for different versions of
left and right 'dot' products. In the odd occasion you might want a
contraction I invariably find it easier to use the appropriate geometric
product and projection.

But this is somewhat redundant. We should produce a library that
efficiently implements the geometric product, projection onto grade,
reverse, and parity. Users can build what they like on top of that. And
each definition in Haskell will  be a two line combination of geometric
product and projection!

Chris

On Tue, Sep 1, 2015 at 3:48 PM, Timo Alho notifications@github.com wrote:

> Well, my experience is rather that they simplify things! Specifically,
> when I found http://arxiv.org/abs/1205.5935 which uses contractions and
> has a nice list of formulas in the end, I became faster and more confident
> in the basic manipulations. What I mean that when using formulas such as
> (1.25b, c) and (1.43) in CA2GC and similar, for me it's easier to keep
> track that the hook points the right way rather than to track the grades of
> the objects explicitly. This is of course the kind of thing that depends
> heavily on what one is used to, and I'm sure varies person to person.
> 
> By saying that one can replace the contractions by a combination of
> geometric product and projection, do you mean that you can essentially
> always subsume the grade conditions to the exceptions already included in
> the definition of the projection?
> 
> Anyway, I think this might be worth discussing with more of the people
> participating who are/will be involved in this project. There's an AGACSE
> 2015 Facebook group, with Dietmar Hildenbrand, Pierre Mechant, Nick
> Okamoto, Pablo Colapinto and others, so there's a reasonably diverse
> sampling of the community. What do you think about wrestling this matter in
> there? In general of course pull requests should be handled here in GitHub,
> but this notational matter affects basically any written output we produce.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga/Formulas/pull/1#issuecomment-136748482.

## 

Dr Chris Doran
Director of Studies, Sidney Sussex College
Technology Entrepreneur, ARM

**Comment by lukeburns** [comment]
On the matter of contractions, I don't have an opinion. If they're helpful, use 'em. But I don't think their position at the very top of this document reflects their usefulness. 

Since this is a reference, it may be worthwhile to simply include both the product+projection and contraction in the formulas. Happy to discuss it more, but don't see it as the most important thing for us to be spending our time on.

Chris, when you're ready to invite others to join you in developing the Haskell library, we can create a new repository under the organization, if that's what you'd like to do. This repo is just intended to be a general GA reference.

**Comment by lukeburns** [comment]
Also, if you'd like to see particular changes made to this document, feel free to fork the project, make the changes you want to see, and submit a pull request, which is what Timo did.

**Comment by timoalho** [comment]
Ok, we've got slightly different purposes here. As Luke said, the point of this repo is just to build a unified collection of formulas for day to day calculations (of course, the hope is that it will turn out useful in other things we want to do here). The best existing such collection that I know of at the moment is Chisolm's, but he omits some useful formulas from CA2GC and obviously has no derivative formulas at all. Anyway, for the collection to be useful we have to fix the notation...

By projection you mean grade projection every time, right?

You're of course right about the Haskell library, with the primitives in place it'll be trivial to define anything one prefers, so for that this is not that important. I'm looking forward to seeing the library, it'll give me a perfect excuse to finally learn enough Haskell to at least use it (I've read one lengthy tutorial on Haskell, which got me hooked on the ideas, but never actually did anything with it)!

**Comment by chrisjldoran** [comment]
I've uploaded my current WIP Haskell implementation of GA. Currently this
is all in 1 file, called newga.hs. It needs a lot of work, but I believe
the core design decisions are the right ones. In particular, multivectors
are stored as a newtype and added to the Num class, so we can use + and *
for multivectors. This makes code really simple to read.

Some obvious work that is required:

-Test core routines
- Decide which functions to expose (only a handful needed as multivectors
  will be an ADT)
- Refactor code into some smaller files
- Optimise (need memoization for blade product and grade operations)
  ....

Chris

Chris

On Tue, Sep 1, 2015 at 9:47 PM, Timo Alho notifications@github.com wrote:

> Ok, we've got slightly different purposes here. As Luke said, the point of
> this repo is just to build a unified collection of formulas for day to day
> calculations (of course, the hope is that it will turn out useful in other
> things we want to do here). The best existing such collection that I know
> of at the moment is Chisolm's, but he omits some useful formulas from CA2GC
> and obviously has no derivative formulas at all. Anyway, for the collection
> to be useful we have to fix the notation...
> 
> By projection you mean grade projection every time, right?
> 
> You're of course right about the Haskell library, with the primitives in
> place it'll be trivial to define anything one prefers, so for that this is
> not that important. I'm looking forward to seeing the library, it'll give
> me a perfect excuse to finally learn enough Haskell to at least use it
> (I've read one lengthy tutorial on Haskell, which got me hooked on the
> ideas, but never actually did anything with it)!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga/Formulas/pull/1#issuecomment-136856291.

## 

Dr Chris Doran
Director of Studies, Sidney Sussex College
Technology Entrepreneur, ARM

**Comment by lukeburns** [comment]
Merging this to get us moving. No reason for matters of convention to stall us.

Great news Chris – see my post on the FB group.

**Pull request merged**
