### PR TITLE
Initial batch of multivector directed derivatives

### PR DESCRIPTION
**Pull request by timoalho**
I've returned to this work after quite a while, as I once again found myself rederiving the simple basic stuff over and over again.

The new content is a few more definitions, and then a number of basic multivector directed derivatives. I started from those, as opposed to the vector derivatives, since the multivector case for blades is often not much more difficult to derive than the vector case, but of course immediately implies the vector case. The only real extra complication in the results due to the multivectors this far is that for some of the projections one could simplify A-P(A) to rejections, when A is a vector. Also, I derive the directed formulas, since the vector/multivector derivative follows immediately (since the directed derivative is always linear in the direction, so it's just a matter of mv-differentiating a linear function), but the other way around does not. Also, the chain rule applies to the directed derivative, not the multivector derivative (i.e., if you only know the mv-derivative of a function, that does not allow you to derive the mv-derivative of its composite function with something else).

Of course, I have nothing against later writing down the simplified forms for vector derivatives and so on, although we probably have to decide on some logic as to how closely related versions we will actually write explicitly.

Also, some of the formatting is currently admittedly clumsy, I'm very open for suggestions on how to improve that. The same goes for notation (I haven't actually used the contractions in these new formulas, so that specific bogeyman shouldn't show up :) ).

I decided to finally start using the proofs.pdf, as the multivector derivatives follow nicely in logical sequence, so it was actually easier to just prove them rather than to hunt each formula down in the literature. Also, I derive these for an arbitrary signature, and many authors (like Hitzer) don't.

Sorry for the large pile of new formulas, that's because I had for a long time some of the ones I really needed written down without proofs, and I only got around to typing those down now. I'll try to do more bite-sized chunks in the future.

### CODE REVIEW

**Comment by lukeburns** [comment]
Hey Timo, thanks for your patience with me on this. Proofs M25, M26, M28, 29, 30, 31 lgtm. Might be worth noting that you need 1.20a from Chp 1 of CAGC in M26. You can probably combine M29 and M30 into one label.

Question: in proof of M27, how do you get (A * X \rev) \hat X = (A * \hat X) X^\rev? Also what is your definition of P_X(A)?

**Comment by timoalho** [comment]
Re proof of M27: note that this is for the part "X is a simple blade", in which case both \hat X and X^\rev amount to multiplication of X by a scalar, which I can freely move between the various factors of X. Definition of P_X(A) is formula (10) in the main text (note again that the claim concerning the projection is only made for X a simple blade).

You're right that strictly speaking I need (1.20a) from GA2GC in M26. And also I'm inconsistent with having two labels for (29), (30), and only one for (31). I'll go with your suggestion to combine (29) and (30), commit following in a moment. Note that references will change, so in the next comment you'll have to specify which version you're referring to :)

**Comment by timoalho** [comment]
Done, also fixed a few typos etc, see commit comments

**Comment by lukeburns** [comment]
👍

**Pull request merged**
